let mySprite = sprites.create(assets.image`koala`, SpriteKind.Player)
tiles.setTilemap(tilemap`mainTileMap`)
controller.moveSprite(mySprite)
scene.centerCameraAt(80, 60)
scene.cameraFollowSprite(mySprite)
